version: '3.4'

services:
  tiendaservicios.api.autor:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6104:80"

  tiendaservicios.api.libro:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6105:80"

